<a href="https://colab.research.google.com/github/Harshvardhan-Moundekar/Machine_Learning/blob/main/MSPA_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<H1>MSPA - 02</H1>
Implement Ensemble methods (bagging and boosting)

In [6]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [5]:
file_path = "/content/drive/MyDrive/6TH SEM/Machine Learning Lab/train_clean_data.csv"
df = pd.read_csv(file_path)
df.head()

Unnamed: 0   Loan_ID Dependents  ApplicantIncome  CoapplicantIncome  \
0           1  LP001003          1             4583             1508.0   
1           2  LP001005          0             3000                0.0   
2           3  LP001006          0             2583             2358.0   
3           4  LP001008          0             6000                0.0   
4           5  LP001011          2             5417             4196.0   

   LoanAmount  Loan_Amount_Term  Credit_History  gender_Male  married_Yes  \
0       128.0             360.0             1.0            1            1   
1        66.0             360.0             1.0            1            1   
2       120.0             360.0             1.0            1            1   
3       141.0             360.0             1.0            1            0   
4       267.0             360.0             1.0            1            1   

   education_Not Graduate  property_area_Semiurban  property_area_Urban  \
0                       0                        0                    0   
1                       0                        0                    1   
2                       1                        0                    1   
3                       0                        0                    1   
4                       0                        0                    1   

   self_employed_Yes  Loan_status_Y  
0                  0              0  
1                  1              1  
2                  0              1  
3                  0              1  
4                  1              1

In [7]:
df.dropna(axis=0, inplace=True)

In [9]:
x = df.drop(['Loan_status_Y','Loan_ID','Dependents'],axis=1)
y = df['Loan_status_Y']

#split dataset into train and test(70 - 30)
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y, test_size=0.3, random_state=42)

In [21]:
#Applying Random Forest Algorithm
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [22]:
rfc_pred = rfc.predict(x_test)

In [23]:
from sklearn.metrics import classification_report , confusion_matrix

print(confusion_matrix(y_test,rfc_pred))

[[ 20  19]
 [  3 114]]


In [29]:
#Accuracy of the model
from sklearn.metrics import accuracy_score
print("Accuracy of Random Forest Algorithm : ",accuracy_score(y_test,rfc_pred))

Accuracy of Random Forest Algorithm :  0.8589743589743589


In [26]:
#Applying Adaboost Algorithm
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(n_estimators=100)
ada.fit(x_train, y_train)


AdaBoostClassifier(n_estimators=100)

In [27]:
ada_pred = ada.predict(x_test)
print(confusion_matrix(y_test,ada_pred))

[[ 18  21]
 [  5 112]]


In [28]:
print("Accuracy of AdaBoost Algorithm : ", accuracy_score(y_test,ada_pred))

Accuracy of AdaBoost Algorithm :  0.8333333333333334


In [33]:
#Apply XGBoost Algorithm
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=100)
xgb.fit(x_train, y_train)



XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [36]:
xgb_pred = xgb.predict(x_test)
print(confusion_matrix(y_test,xgb_pred))


[[ 24  15]
 [  7 110]]


In [37]:
print("Accuracy of XGBoost Algorithm : ", accuracy_score(y_test,xgb_pred))

Accuracy of XGBoost Algorithm :  0.8589743589743589


In [39]:
#Apply Bagging and Boosting techniques
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier

#Apply those model
bag = BaggingClassifier(n_estimators=100)
bag.fit(x_train, y_train)

BaggingClassifier(n_estimators=100)

In [40]:
gbc = GradientBoostingClassifier(n_estimators=100)
gbc.fit(x_train, y_train)

GradientBoostingClassifier()

In [41]:
bag_pred = bag.predict(x_test)
gbc_pred = gbc.predict(x_test)

print(confusion_matrix(y_test,bag_pred))
print(confusion_matrix(y_test,gbc_pred))

print("Accuracy of Bagging Algorithm : ", accuracy_score(y_test,bag_pred))
print("Accuracy of Gradient Boosting Algorithm : ", accuracy_score(y_test,gbc_pred))

[[ 19  20]
 [  4 113]]
[[ 18  21]
 [ 10 107]]
Accuracy of Bagging Algorithm :  0.8461538461538461
Accuracy of Gradient Boosting Algorithm :  0.8012820512820513


In [43]:
#Give me a Accuracy of all model
print("Accuracy of Random Forest Algorithm : ",accuracy_score(y_test,rfc_pred))
print("Accuracy of AdaBoost Algorithm : ", accuracy_score(y_test,ada_pred))
print("Accuracy of XGBoost Algorithm : ", accuracy_score(y_test,xgb_pred))
print("Accuracy of Bagging Algorithm : ", accuracy_score(y_test,bag_pred))
print("Accuracy of Gradient Boosting Algorithm : ", accuracy_score(y_test,gbc_pred))


Accuracy of Random Forest Algorithm :  0.8589743589743589
Accuracy of AdaBoost Algorithm :  0.8333333333333334
Accuracy of XGBoost Algorithm :  0.8589743589743589
Accuracy of Bagging Algorithm :  0.8461538461538461
Accuracy of Gradient Boosting Algorithm :  0.8012820512820513


In [45]:

#which one is the best one
print("Best one is XGBoosting Algorithm")
#why it is the best

Best one is XGBoosting Algorithm
